# Generated by Django 4.1.3 on 2022-12-01 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_order_date_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 21, 15, 52, 302877, tzinfo=datetime.timezone.utc)),
        ),
    ]
