# Generated by Django 4.1.3 on 2022-12-01 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 21, 16, 39, 517757, tzinfo=datetime.timezone.utc)),
        ),
    ]
