# Generated by Django 4.1.3 on 2022-12-01 22:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_address',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user_address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cart_item',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.shopping_cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 22, 16, 51, 201095, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Site_User',
        ),
        migrations.DeleteModel(
            name='User_Address',
        ),
    ]
