# Generated by Django 4.1.3 on 2022-12-02 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_user_address_address_remove_user_address_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 13, 5, 19, 525036, tzinfo=datetime.timezone.utc)),
        ),
    ]
