# Generated by Django 4.1.3 on 2022-12-02 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 19, 47, 14, 889430, tzinfo=datetime.timezone.utc)),
        ),
    ]
