# Generated by Django 4.1.3 on 2022-12-06 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_cart_item_ordered_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 14, 29, 43, 308558, tzinfo=datetime.timezone.utc)),
        ),
    ]
