# Generated by Django 4.1.3 on 2022-11-27 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_remove_site_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 17, 18, 5, 467362, tzinfo=datetime.timezone.utc)),
        ),
    ]
