# Generated by Django 4.1.3 on 2022-11-27 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 17, 29, 13, 494629, tzinfo=datetime.timezone.utc)),
        ),
    ]
