# Generated by Django 4.1.3 on 2022-11-21 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_order_user_order_address_order_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 14, 17, 48, 639988, tzinfo=datetime.timezone.utc)),
        ),
    ]
