# Generated by Django 4.1.3 on 2022-11-21 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='posta_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 15, 2, 42, 393473, tzinfo=datetime.timezone.utc)),
        ),
    ]
