# Generated by Django 4.1.3 on 2022-11-21 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_address_posta_code_alter_order_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='posta_code',
            new_name='postal_code',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 15, 3, 31, 502365, tzinfo=datetime.timezone.utc)),
        ),
    ]
