# Generated by Django 4.1 on 2022-11-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_discount_product_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
