# Generated by Django 4.1.3 on 2022-11-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_category_id_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
