# Generated by Django 4.1 on 2022-11-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_discount_price_alter_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
