# Generated by Django 4.1.3 on 2022-11-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_category_id_product_category_and_more'),
        ('products', '0011_alter_product_product_description'),
    ]

    operations = [
    ]
